# 允许本地连接
local   all             all                                     trust
# 允许IPv4连接
host    all             all             127.0.0.1/32            trust
# 允许同一网络中的其他容器连接
host    all             all             0.0.0.0/0               md5
# 允许IPv6连接
host    all             all             ::1/128                 trust